In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Robin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Robin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Robin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 10.1 MB/s eta 0:00:01
   -------- ------------------------------- 2.1/9.9 MB 6.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 5.9 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 6.3 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.7 MB/s  0:00:01
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 7.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.1 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 7.1 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 7.0 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 7.0 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 7.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.1 MB/s  0:00:02
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.3

WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 22, 21, 20],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"],
    "Marks": [85, 72, 91, 68, 78]
}
df=pd.DataFrame(data)

In [4]:
df.head()

  Student  Age Department  Marks
0       A   20        CSE     85
1       B   21         IT     72
2       C   22        CSE     91
3       D   21        ECE     68
4       E   20         IT     78

In [5]:
df.tail()

  Student  Age Department  Marks
0       A   20        CSE     85
1       B   21         IT     72
2       C   22        CSE     91
3       D   21        ECE     68
4       E   20         IT     78

In [7]:
df.shape

(5, 4)

In [9]:
df.columns

Index(['Student', 'Age', 'Department', 'Marks'], dtype='str')

In [12]:
df.dtypes

Student         str
Age           int64
Department      str
Marks         int64
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [14]:
df.describe()

            Age      Marks
count   5.00000   5.000000
mean   20.80000  78.800000
std     0.83666   9.364828
min    20.00000  68.000000
25%    20.00000  72.000000
50%    21.00000  78.000000
75%    21.00000  85.000000
max    22.00000  91.000000

In [16]:
df["Department"].unique()

<StringArray>
['CSE', 'IT', 'ECE']
Length: 3, dtype: str

In [17]:
df['Department'].nunique()

3

In [18]:
df['Department'].value_counts()

Department
CSE    2
IT     2
ECE    1
Name: count, dtype: int64

In [19]:
df.isnull().sum()

Student       0
Age           0
Department    0
Marks         0
dtype: int64

In [20]:
df['Marks'].max()

np.int64(91)

In [21]:
df[df['Marks']==df['Marks'].max()]

  Student  Age Department  Marks
2       C   22        CSE     91

In [22]:
df['Marks'] +=2

In [23]:
df

  Student  Age Department  Marks
0       A   20        CSE     87
1       B   21         IT     74
2       C   22        CSE     93
3       D   21        ECE     70
4       E   20         IT     80

In [24]:
df['Marks']=df['Marks']+2

In [25]:
df

  Student  Age Department  Marks
0       A   20        CSE     89
1       B   21         IT     76
2       C   22        CSE     95
3       D   21        ECE     72
4       E   20         IT     82

In [26]:
df['Marks']=df['Marks'].apply(lambda x:x+2)
print(df)

  Student  Age Department  Marks
0       A   20        CSE     91
1       B   21         IT     78
2       C   22        CSE     97
3       D   21        ECE     74
4       E   20         IT     84

In [28]:
df.loc[df['Student']=='E', 'Marks'] = df.loc[df['Student']=='E', 'Marks'] + 6
print(df)

  Student  Age Department  Marks
0       A   20        CSE     91
1       B   21         IT     78
2       C   22        CSE     97
3       D   21        ECE     74
4       E   20         IT     95

In [29]:
df.at[1,'Marks']+=2
print(df)

  Student  Age Department  Marks
0       A   20        CSE     91
1       B   21         IT     80
2       C   22        CSE     97
3       D   21        ECE     74
4       E   20         IT     95

In [4]:
import pandas as pd

data = {
    "Student": [
        "Paul", "John", "Alex", "Mary", "David",
        "Sophia", "James", "Emma", "Daniel", "Olivia"
    ],
    "Math": [85, 72, 90, 88, 76, 95, 67, 82, 79, 91],
    "Science": [80, 78, 95, 84, 70, 96, 65, 88, 81, 92],
    "English": [78, 85, 89, 90, 75, 94, 72, 80, 77, 93],
    "City": [
        "Chennai", "Madurai", "Chennai", "Coimbatore", "Madurai",
        "Chennai", "Salem", "Coimbatore", "Madurai", "Chennai"
    ],
    "Gender": [
        "Male", "Male", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    "Attendance": [92, 85, 98, 96, 88, 99, 80, 94, 90, 97]
}

df = pd.DataFrame(data)

print(df)

  Student  Math  Science  English        City  Gender  Attendance
0    Paul    85       80       78     Chennai    Male          92
1    John    72       78       85     Madurai    Male          85
2    Alex    90       95       89     Chennai    Male          98
3    Mary    88       84       90  Coimbatore  Female          96
4   David    76       70       75     Madurai    Male          88
5  Sophia    95       96       94     Chennai  Female          99
6   James    67       65       72       Salem    Male          80
7    Emma    82       88       80  Coimbatore  Female          94
8  Daniel    79       81       77     Madurai    Male          90
9  Olivia    91       92       93     Chennai  Female          97

In [2]:
print(df.loc[df['Student']=='mary'])

Empty DataFrame
Columns: [Student, Math, Science, English, City, Gender, Attendance]
Index: []

In [5]:
print(df.loc[df['Student']=='Mary','Math'])

3    88
Name: Math, dtype: int64

In [6]:
print(df.loc[df["Student"] == "Paul", ["Math", "Science"]])

   Math  Science
0    85       80

In [7]:
print(df.loc[df['Math'] > 90,['Student','Math']])

  Student  Math
5  Sophia    95
9  Olivia    91

In [9]:
print(df.loc[df['City']=='Chennai',['Student','Science','Math','English']])

  Student  Science  Math  English
0    Paul       80    85       78
2    Alex       95    90       89
5  Sophia       96    95       94
9  Olivia       92    91       93

In [16]:
print(df.loc[(df['Gender']=='Male') & (df['Math']>80),['Student','City']])

  Student     City
0    Paul  Chennai
2    Alex  Chennai

In [21]:
print(df[df['Gender']=='Male'].value_counts())

Student  Math  Science  English  City     Gender  Attendance
Paul     85    80       78       Chennai  Male    92            1
John     72    78       85       Madurai  Male    85            1
Alex     90    95       89       Chennai  Male    98            1
David    76    70       75       Madurai  Male    88            1
James    67    65       72       Salem    Male    80            1
Daniel   79    81       77       Madurai  Male    90            1
Name: count, dtype: int64

In [22]:
print(df['Gender'].value_counts())

Gender
Male      6
Female    4
Name: count, dtype: int64

In [24]:
print(df['Gender'].value_counts(normalize=True))

Gender
Male      0.6
Female    0.4
Name: proportion, dtype: float64

In [8]:
print(df[df['Attendance']>90])

  Student  Math  Science  English        City  Gender  Attendance
0    Paul    85       80       78     Chennai    Male          92
2    Alex    90       95       89     Chennai    Male          98
3    Mary    88       84       90  Coimbatore  Female          96
5  Sophia    95       96       94     Chennai  Female          99
7    Emma    82       88       80  Coimbatore  Female          94
9  Olivia    91       92       93     Chennai  Female          97

In [ ]:
print(df[df['Attendance']>90])

  Student  Math  Science  English        City  Gender  Attendance
0    Paul    85       80       78     Chennai    Male          92
2    Alex    90       95       89     Chennai    Male          98
3    Mary    88       84       90  Coimbatore  Female          96
5  Sophia    95       96       94     Chennai  Female          99
7    Emma    82       88       80  Coimbatore  Female          94
9  Olivia    91       92       93     Chennai  Female          97

In [10]:
print(df[(df['Gender']=='Female')& (df['Attendance']>=94)])

  Student  Math  Science  English        City  Gender  Attendance
3    Mary    88       84       90  Coimbatore  Female          96
5  Sophia    95       96       94     Chennai  Female          99
7    Emma    82       88       80  Coimbatore  Female          94
9  Olivia    91       92       93     Chennai  Female          97

In [2]:
import pandas as pd
T1=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/refs/heads/main/titanic.csv")
#print(T1)
display(T1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
Survival_rate = T1.groupby('Survived')
display(Survival_rate)
Survival_rate.apply(display)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
884,885,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
875,876,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

Empty DataFrame
Columns: [PassengerId, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [2]:
import pandas as pd
airbnb = pd.read_csv('https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/airbnb.csv?raw=true', index_col = 'Unnamed: 0')
airbnb

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45$,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135$,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","(40.7007, -73.99517)",Entire home/apt,150$,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","(40.79169, -73.97498)",Entire home/apt,86$,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","(40.71884, -73.98354)",Private room,160$,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","(40.80379, -73.95257)",Entire home/apt,105$,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","(40.79531, -73.9333)",Entire home/apt,125$,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","(40.68266, -73.96743000000002)",Entire home/apt,100$,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","(40.68832, -73.96366)",Entire home/apt,450$,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","(40.76174, -73.96625)",Private room,90$,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06

In [4]:
a=airbnb.duplicated().sum()

In [6]:
print(a)

13

In [8]:
airbnb.info()

<class 'pandas.DataFrame'>
RangeIndex: 10019 entries, 0 to 10018
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   listing_id          10019 non-null  int64
 1   name                10014 non-null  str
 2   host_id             10019 non-null  int64
 3   host_name           10017 non-null  str
 4   neighbourhood_full  10019 non-null  str
 5   coordinates         10019 non-null  str
 6   room_type           10019 non-null  str
 7   price               9781 non-null   str
 8   number_of_reviews   10019 non-null  int64
 9   last_review         7944 non-null   str
 10  reviews_per_month   7944 non-null   float64
 11  availability_365    10019 non-null  int64
 12  rating              7944 non-null   float64
 13  number_of_stays     7944 non-null   float64
 14  5_stars             7944 non-null   float64
 15  listing_added       10019 non-null  str
dtypes: float64(4), int64(4), str(8)
memory usage: 1.2 MB

In [19]:
b = airbnb[airbnb.duplicated(keep=False)]
display(b)

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
368,17861841,THE CREATIVE COZY ROOM,47591528,Janessa,"Brooklyn, Sheepshead Bay","(40.59211, -73.94126999999997)",Private room,99$,13,2019-05-23,0.52,82,4.806590,15.6,0.937422,2018-11-17
1145,253806,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,"Brooklyn, Greenpoint","(40.73652, -73.95236)",Entire home/apt,199$,43,2019-07-02,0.47,60,4.620238,51.6,0.861086,2018-12-27
1338,32610834,Manhattan by the water!,12132369,Omar,"Manhattan, Kips Bay","(40.73767, -73.97384)",Entire home/apt,150$,0,NaN,NaN,9,NaN,NaN,NaN,2018-06-28
1658,35646737,"Private Cabins @ Chelsea, Manhattan",117365574,Maria,"Manhattan, Chelsea","(40.74946, -73.99627)",Private room,85$,1,2019-06-22,1.00,261,4.951714,1.2,0.671388,2018-12-17
2118,33346762,2BR Apartment in Brownstone Brooklyn!,50321289,Avery,"Brooklyn, Bedford-Stuyvesant","(40.682, -73.95681)",Entire home/apt,140$,4,2019-06-14,1.58,4,4.013393,4.8,0.719591,2018-12-09
3007,17861841,THE CREATIVE COZY ROOM,47591528,Janessa,"Brooklyn, Sheepshead Bay","(40.59211, -73.94126999999997)",Private room,99$,13,2019-05-23,0.52,82,4.806590,15.6,0.937422,2018-11-17
3065,16518377,East Village 1BR Apt with all the amenities,3012457,Cody,"Manhattan, East Village","(40.7235, -73.97963)",Entire home/apt,200$,3,2018-07-10,0.16,0,4.676670,3.6,0.694443,2018-01-04
3340,35646737,"Private Cabins @ Chelsea, Manhattan",117365574,Maria,"Manhattan, Chelsea","(40.74946, -73.99627)",Private room,85$,1,2019-06-22,1.00,261,4.951714,1.2,0.671388,2018-12-17
5025,33831116,Sonder | Stock Exchange | Collected 1BR + Laundry,219517861,Sonder (NYC),"Manhattan, Financial District","(40.70621, -74.01199)",Entire home/apt,229$,5,2019-06-15,1.92,350,4.026379,6.0,0.601737,2018-12-10
5077,33831116,Sonder | Stock Exchange | Collected 1BR + Laundry,219517861,Sonder (NYC),"Manhattan, Financial District","(40.70621, -74.01199)",Entire home/apt,229$,5,2019-06-15,1.92,350,4.026379,6.0,0.601737,2018-12-10
5236,29844951,Cozy Home In Queens,49946447,Rah,"Queens, Jamaica","(40.68842, -73.77677)",Private room,50$,1,2019-03-19,0.27,311,4.792923,1.2,0.701232,2018-09-13
5246,22014840,Sunny Bedroom Only 1 Metro Stop to Manhattan,32093643,Scarlett,"Manhattan, Roosevelt Island","(40.76211, -73.94887)",Private room,70$,2,2018-01-07,0.11,0,4.024336,2.4,0.719426,2017-07-04
5251,19477677,Huge sunny room next to subway!,25038748,Justin,"Manhattan, Harlem","(40.82119, -73.95583)",Private room,70$,11,2019-05-11,0.45,0,3.074890,13.2,0.631619,2018-11-05
5397,16518377,East Village 1BR Apt with all the amenities,3012457,Cody,"Manhattan, East Village","(40.7235, -73.97963)",Entire home/apt,200$,3,2018-07-10,0.16,0,4.676670,3.6,0.694443,2018-01-04
5454,21106251,Private Bedroom in Great Brooklyn Apartment,25354313,Tommy,"Brooklyn, Crown Heights","(40.67359, -73.95812)",Private room,45$,9,2019-06-22,0.43,0,3.779114,10.8,0.738191,2018-12-17
5861,23990868,1 Bedroom in Luxury Building,4447548,Grace,"Brooklyn, Bedford-Stuyvesant","(40.69336, -73.94453)",Entire home/apt,88$,8,2019-06-16,0.56,18,4.164548,9.6,0.640106,2018-12-11
6068,22014840,Sunny Bedroom Only 1 Metro Stop to Manhattan,32093643,Scarlett,"Manhattan, Roosevelt Island","(40.76211, -73.94887)",Private room,70$,2,2018-01-07,0.11,0,4.024336,2.4,0.719426,2017-07-04
6085,33346762,2BR Apartment in Brownstone Brooklyn!,50321289,Avery,"Brooklyn, Bedford-Stuyvesant","(40.682, -73.95681)",Entire home/apt,140$,4,2019-06-14,1.58,4,4.013393,4.8,0.719591,2018-12-09
6132,23990868,1 Bedroom in Luxury Building,4447548,Grace,"Brooklyn, Bedford-Stuyvesant","(40.69336, -73.94453)",Entire home/apt,88$,8,2019-06-16,0.56,18,4.164548,9.6,0.640106,2018-12-11
6313,32610834,Manhattan by the water!,12132369,Omar,"Manhattan, Kips Bay","(40.73767, -73.97384)",Entire home/apt,150$,0,NaN,NaN,9,NaN,NaN,NaN,2018-06-28
6438,19477677,Huge sunny room next to subway!,25038748,Justin,"Manhattan, Harlem","(40.82119, -73.95583)",Private room,70$,11,2019-05-11,0.45,0,3.074890,13.2,0.631619,2018-11-05
6562,253806,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,"Brooklyn, Greenpoint","(40.73652, -73.95236)",Entire home/apt,199$,43,2019-07-02,0.47,60,4.620238,51.6,0.861086,2018-12-27
6832,21106251,Private Bedroom in Great Brooklyn Apartment,25354313,Tommy,"Brooklyn, Crown Heights","(40.67359, -73.95812)",Private room,45$,9,2019-06-22,0.43,0,3.779114,10.8,0.738191,2018-12-17
7116,26554879,East Village/Union Square Flat,17400431,Bob,"Manhattan, East Village","(40.73177, -73.98691)",Entire home/apt,179$,32,2019-06-26,2.92,12,3.125513,38.4,0.631764,2018-12-21
7769,26554879,East Village/Union Square Flat,17400431,Bob,"Manhattan, East Village","(40.73177, -73.98691)",Entire home/apt,179$,32,2019-06-26,2.92,12,3.125513,38.4,0.631764,2018-12-21
9425,29844951,Cozy Home In Queens,49946447,Rah,"Queens, Jamaica","(40.68842, -73.77677)",Private room,50$,1,2019-03-19,0.27,311,4.792923,1.2,0.701232,2018-09-13

In [15]:
airbnb.isnull().sum()

listing_id               0
name                     5
host_id                  0
host_name                2
neighbourhood_full       0
coordinates              0
room_type                0
price                  238
number_of_reviews        0
last_review           2075
reviews_per_month     2075
availability_365         0
rating                2075
number_of_stays       2075
5_stars               2075
listing_added            0
dtype: int64